# Generated by Django 5.2.5 on 2026-05-13 18:56

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='blood_group',
            field=models.CharField(blank=True, choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('O+', 'O+'), ('O-', 'O-'), ('AB+', 'AB+'), ('AB-', 'AB-')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='user_image'),
        ),
    ]
