# Generated by Django 5.2.5 on 2025-08-31 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_userimage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserImage',
        ),
    ]
