# Generated by Django 5.2.5 on 2025-09-05 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donation', '0002_alter_donation_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Accepted', 'Accepted'), ('Donated', 'Donated'), ('Cancelled', 'Cancelled')], default='Pending', max_length=20),
        ),
    ]
