# Generated by Django 5.2.5 on 2025-08-25 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blood_request', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloodrequest',
            name='status',
            field=models.CharField(choices=[('Donated', 'Donated'), ('Pending', 'Pending'), ('Accepted', 'Accepted'), ('Canceled', 'Canceled')], default='Pending', max_length=20),
        ),
    ]
