# Generated by Django 5.2.5 on 2025-08-25 19:36

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blood_request', '0003_rename_location_bloodrequest_hospital_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloodrequest',
            name='donation_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bloodrequest',
            name='volume',
            field=models.CharField(default='2 bags', help_text='Volume of blood needed (e.g., 3 bags)', max_length=50),
            preserve_default=False,
        ),
    ]
