# Generated by Django 5.2.5 on 2025-08-31 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blood_request', '0004_bloodrequest_donation_date_bloodrequest_volume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloodrequest',
            name='volume',
            field=models.CharField(help_text='(e.g., 3 bags)', max_length=50),
        ),
    ]
